function MapInfo = NicheGeneration(ReadInfo, InfoInitialPoint, Occupation, show)
% NicheGeneration generates a niche map for a virtual species based on
% environmental variables.
%
% INPUTS:
%   ReadInfo: a structure generated by the 'ReadLayers' function.
%   InfoInitialPoint: a structure generated by the 'InitialPoint' function.
%   Occupation: an integer with the occupation value ([0,1)).
%   show: boolean variable (true, false) to show the resulting niche map.
%
% OUTPUTS:
%   MapInfo: a structure with the following fields:
%       - Map: a matrix representing the niche map.
%       - SortNormDistance: a vector of sorted and normalized distances.
%       - NormDistance: a vector of normalized distances.

    % Start timer
    tic 

    % Read climate variables
    Indicator = ReadInfo.Indicator;  % Indicator matrix
    Dimension = ReadInfo.Dimensions(1);  % Dimension of the map
    R = ReadInfo.R;  % Geographic reference object
    [Dim1, Dim2] = size(ReadInfo.Map);  % Size of the map
    Map = nan(Dim1, Dim2);  % Initialize the niche map

    % Extract initial point information
    idx = InfoInitialPoint.idx;  % Index of the initial point
    SortNormDistance = InfoInitialPoint.SortNormDistance;  % Sorted and normalized distances

    % Calculate the limit for the niche map
    limit = round(Dimension * Occupation); 

    % Normalize the distances and set distances beyond the limit to 0
    NormDistance = zeros(1,length(SortNormDistance));
    SortNormDistance(limit : end) = 0;
    IndexSortNorm = 1 : limit - 1;
    SortNormDistance(IndexSortNorm) = normalize(SortNormDistance(IndexSortNorm), 2, 'range');
    
    % Assign the normalized distances to the niche map
    NormDistance(idx) = SortNormDistance;
    Map(~Indicator) = NormDistance;

    % Plot niche map if show is true
    if show
        clf
        geoshow(Map, R, 'DisplayType', 'surface');
        contourcmap('jet', 0 : 0.05 : 1, 'colorbar', 'on', 'location', 'vertical')
    end

    % Save output in a structure
    MapInfo.Map = Map;
    MapInfo.SortNormDistance = SortNormDistance;
    MapInfo.NormDistance = NormDistance;
    
    % Stop timer
    toc      
end
